# Generated by Django 5.2 on 2025-07-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='category', help_text="Material icon name (e.g., 'home', 'shopping_cart').", max_length=50),
        ),
    ]
