# Generated by Django 5.2 on 2025-07-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='category', help_text="Flutter icon name (e.g., 'shopping_cart', 'phone_android')", max_length=50),
        ),
    ]
